name: Documentation Improvement
description: Report missing, incorrect, or unclear documentation (will result in a docs: commit)
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! This issue will typically result in a `docs:` commit.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Setup/Installation Guide
        - Code Comments
        - Architecture Documentation
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What is wrong, missing, or unclear in the current documentation?
      placeholder: The documentation doesn't explain...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located (file path, URL, section)?
      placeholder: File path or URL...
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve or clarify this documentation?
      placeholder: It should explain...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or examples about the documentation issue here.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the required information above
          required: true
